version: 0.2
env:
  variables:
    AWS_REGION: us-east-1
    ECR_REPO: secure-health-api
    CONTAINER_NAME: secure-health-api
phases:
  pre_build:
    commands:
      - echo "Logging in to ECR..."
      - AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - REPO_URI=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO}
      - COMMIT_SHA=${CODEBUILD_RESOLVED_SOURCE_VERSION}
      - IMAGE_TAG=${COMMIT_SHA:0:7}-${CODEBUILD_BUILD_NUMBER}  # <-- Added build number
      - aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com
  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t ${REPO_URI}:${IMAGE_TAG} ./app
  post_build:
    commands:
      - echo "Pushing Docker image..."
      - docker push ${REPO_URI}:${IMAGE_TAG}
      - echo "Writing imagedefinitions.json..."
      - printf '[{"name":"%s","imageUri":"%s"}]' "${CONTAINER_NAME}" "${REPO_URI}:${IMAGE_TAG}" > imagedefinitions.json
      - cat imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json